name: Extract Files and Save to Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  extract-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract archive into repo folder
        run: |
          unzip -o evm-wallet.zip -d 
      - name: Check extracted files
        run: ls -R

      - name: Add files to Git
        run: |
          git add 
